name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install Python dependencies and CDK
        run: |
          python -m pip install --upgrade pip
          npm install -g aws-cdk
          
      - name: Test CDK
        run: |
          cdk --version